# Generated by Django 2.2.10 on 2020-02-21 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeigbourHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NeigbourHoodMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neigbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='neigbour.NeigbourHood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_neigbourhood', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('neigbourhood', 'user')},
            },
        ),
        migrations.AddField(
            model_name='neigbourhood',
            name='members',
            field=models.ManyToManyField(through='neigbour.NeigbourHoodMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
